name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script 
        run: echo ${{ env.MY_VAR }}
