name: AnyViewer Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
         Invoke-WebRequest -Uri "https://www.dropbox.com/sh/l567nu2ff84q4dr/AACTILIbK9bi5yQLtp221pTJa/down.bat?dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Save secrets to file
        run: |
          echo "EMAIL_SECRET=chamoddisala41@gmail.com" > secrets.txt
          echo "PASSWORD_SECRET=Chamod@123" >> secrets.txt
          python login.py

      - name: Time Counter
        run: Start-Sleep -Seconds 500
