name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cmd /c down.bat

      - name: Run Python script
        env:
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          PASSWORD_SECRET: ${{ secrets.PASSWORD_SECRET }}
        run: python login.py $Env:EMAIL_SECRET $Env:PASSWORD_SECRET

       - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/ei73gt7vevxck2t/Downloads.bat?dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c start.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 500
